import Link from "next/link";

import { EmptyState } from "@/components/empty-state";
import { RiskBadge } from "@/components/risk-badge";
import { getClinicianDashboardData } from "@/lib/dashboard-data";

export default async function ClinicianDashboardPage() {
  const { data, error } = await getClinicianDashboardData();
  const names = new Map(data.children.map((child) => [child.id, child.displayName]));
  const priority = data.screenings.filter((screening) => screening.risk === "red" || screening.risk === "yellow");
  const requested = data.appointments.filter((appointment) => appointment.status === "requested");
  return <div className="stack"><section><p className="eyebrow">Clinical workspace</p><h1>Follow-up, organised.</h1><p className="lede">Review the children assigned to your care team, respond to appointment requests, and follow up securely with families.</p></section>{error ? <p className="alert">{error}</p> : null}<section className="grid grid-4"><div className="card card-pad"><p className="metric-label">Assigned children</p><p className="metric-value">{data.children.length}</p><p className="metric-note">Access is limited to care assignments</p></div><div className="card card-pad"><p className="metric-label">Priority screenings</p><p className="metric-value">{priority.length}</p><p className="metric-note">Red or yellow latest sessions</p></div><div className="card card-pad"><p className="metric-label">Appointment requests</p><p className="metric-value">{requested.length}</p><p className="metric-note">Awaiting a response</p></div><div className="card card-pad"><p className="metric-label">Messages</p><p className="metric-value">Care</p><p className="metric-note">Secure family conversations</p></div></section><section className="grid grid-2"><div className="card card-pad"><div className="section-head"><div><p className="eyebrow">Needs review</p><h2>Priority screening follow-up</h2></div><Link className="link" href="/clinician/families">All families</Link></div>{priority.length ? <div className="list">{priority.slice(0, 6).map((screening) => <Link className="list-row" href={`/clinician/children/${screening.childId}`} key={screening.id}><span><span className="row-title">{names.get(screening.childId) ?? "Child"}</span><span className="row-subtitle">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(screening.createdAt))} · VTTL {screening.vttlMs === null ? "—" : `${Math.round(screening.vttlMs)} ms`}</span></span><RiskBadge risk={screening.risk} /></Link>)}</div> : <EmptyState detail="Follow-up screenings will appear here when available." title="No priority screenings" />}</div><div className="card card-pad"><div className="section-head"><div><p className="eyebrow">Scheduling</p><h2>Appointment requests</h2></div><Link className="link" href="/clinician/appointments">Manage</Link></div>{requested.length ? <div className="list">{requested.slice(0, 5).map((appointment) => <div className="list-row" key={appointment.id}><span><span className="row-title">{names.get(appointment.childId) ?? "Child"}</span><span className="row-subtitle">Requested {appointment.requestedFor ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(appointment.requestedFor)) : "time not specified"}</span></span><span className="badge yellow">Requested</span></div>)}</div> : <EmptyState detail="New family requests appear here." title="No appointment requests" />}</div></section></div>;
}
